[project]
name = "deepsearch-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncio>=3.4.3",
    "dotenv>=0.9.9",
    "openai-agents>=0.0.6",
    "serpapi>=0.1.5",
]
