# model settings
models:
  planner:
    model_name: "DeepSeek-R1"
    temperature: 0.5
    max_tokens: 4000
    tool_choice: "required"
    parallel_tool_calls: false

  summarize:
    model_name: "gpt-4o"
    temperature: 0.7
    max_tokens: 4000

  rewrite:
    model_name: "gpt-4o"
    temperature: 0.7
    max_tokens: 4000

  evaluate:
    model_name: "gpt-4o"
    temperature: 0.7
    max_tokens: 10000

execution:
  max_task_depth: 2
  max_token_usage: 150000
  max_turns: 15
